# -*- coding: utf-8 -*-

"""
    awsecommerceservice.awse_commerce_service_client

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""
from .decorators import lazy_property
from .configuration import Configuration
from .controllers.awse_commerce_service_binding_controller import AWSECommerceServiceBindingController

class AwsecommerceserviceClient(object):

    config = Configuration

    @lazy_property
    def awse_commerce_service_binding(self):
        return AWSECommerceServiceBindingController()



