# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.browse_node_lookup_response

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.operation_request
import awsecommerceservice.models.browse_nodes_243

class BrowseNodeLookupResponse(object):

    """Implementation of the 'BrowseNodeLookupResponse' model.

    TODO: type model description here.

    Attributes:
        operation_request (OperationRequest): TODO: type description here.
        browse_nodes (list of BrowseNodes243): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "operation_request" : "OperationRequest",
        "browse_nodes" : "BrowseNodes"
    }

    def __init__(self,
                 operation_request=None,
                 browse_nodes=None):
        """Constructor for the BrowseNodeLookupResponse class"""

        # Initialize members of the class
        self.operation_request = operation_request
        self.browse_nodes = browse_nodes


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        operation_request = awsecommerceservice.models.operation_request.OperationRequest.from_dictionary(dictionary.get("OperationRequest")) if dictionary.get("OperationRequest") else None
        browse_nodes = None
        if dictionary.get("BrowseNodes") != None:
            browse_nodes = list()
            for structure in dictionary.get("BrowseNodes"):
                browse_nodes.append(awsecommerceservice.models.browse_nodes_243.BrowseNodes243.from_dictionary(structure))

        # Return an object of this model
        return cls(operation_request,
                   browse_nodes)


