# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.cart_create_request_55

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.items

class CartCreateRequest55(object):

    """Implementation of the 'CartCreateRequest55' model.

    TODO: type model description here.

    Attributes:
        merge_cart (string): TODO: type description here.
        items (Items): TODO: type description here.
        response_group (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merge_cart" : "MergeCart",
        "items" : "Items",
        "response_group" : "ResponseGroup"
    }

    def __init__(self,
                 merge_cart=None,
                 items=None,
                 response_group=None):
        """Constructor for the CartCreateRequest55 class"""

        # Initialize members of the class
        self.merge_cart = merge_cart
        self.items = items
        self.response_group = response_group


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        merge_cart = dictionary.get("MergeCart")
        items = awsecommerceservice.models.items.Items.from_dictionary(dictionary.get("Items")) if dictionary.get("Items") else None
        response_group = dictionary.get("ResponseGroup")

        # Return an object of this model
        return cls(merge_cart,
                   items,
                   response_group)


