# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.cart_items

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.cart_item
import awsecommerceservice.models.price

class CartItems(object):

    """Implementation of the 'CartItems' model.

    TODO: type model description here.

    Attributes:
        cart_item (list of CartItem): TODO: type description here.
        sub_total (Price): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cart_item" : "CartItem",
        "sub_total" : "SubTotal"
    }

    def __init__(self,
                 cart_item=None,
                 sub_total=None):
        """Constructor for the CartItems class"""

        # Initialize members of the class
        self.cart_item = cart_item
        self.sub_total = sub_total


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        cart_item = None
        if dictionary.get("CartItem") != None:
            cart_item = list()
            for structure in dictionary.get("CartItem"):
                cart_item.append(awsecommerceservice.models.cart_item.CartItem.from_dictionary(structure))
        sub_total = awsecommerceservice.models.price.Price.from_dictionary(dictionary.get("SubTotal")) if dictionary.get("SubTotal") else None

        # Return an object of this model
        return cls(cart_item,
                   sub_total)


