# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.cart_create_response

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.operation_request
import awsecommerceservice.models.cart

class CartCreateResponse(object):

    """Implementation of the 'CartCreateResponse' model.

    TODO: type model description here.

    Attributes:
        operation_request (OperationRequest): TODO: type description here.
        cart (list of Cart): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "operation_request" : "OperationRequest",
        "cart" : "Cart"
    }

    def __init__(self,
                 operation_request=None,
                 cart=None):
        """Constructor for the CartCreateResponse class"""

        # Initialize members of the class
        self.operation_request = operation_request
        self.cart = cart


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        operation_request = awsecommerceservice.models.operation_request.OperationRequest.from_dictionary(dictionary.get("OperationRequest")) if dictionary.get("OperationRequest") else None
        cart = None
        if dictionary.get("Cart") != None:
            cart = list()
            for structure in dictionary.get("Cart"):
                cart.append(awsecommerceservice.models.cart.Cart.from_dictionary(structure))

        # Return an object of this model
        return cls(operation_request,
                   cart)


