# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.meta_data_164

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.key_value_pair

class MetaData164(object):

    """Implementation of the 'MetaData164' model.

    TODO: type model description here.

    Attributes:
        key_value_pair (list of KeyValuePair): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key_value_pair" : "KeyValuePair"
    }

    def __init__(self,
                 key_value_pair=None):
        """Constructor for the MetaData164 class"""

        # Initialize members of the class
        self.key_value_pair = key_value_pair


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        key_value_pair = None
        if dictionary.get("KeyValuePair") != None:
            key_value_pair = list()
            for structure in dictionary.get("KeyValuePair"):
                key_value_pair.append(awsecommerceservice.models.key_value_pair.KeyValuePair.from_dictionary(structure))

        # Return an object of this model
        return cls(key_value_pair)


