# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.other_categories_similar_products

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.other_categories_similar_product

class OtherCategoriesSimilarProducts(object):

    """Implementation of the 'OtherCategoriesSimilarProducts' model.

    TODO: type model description here.

    Attributes:
        other_categories_similar_product (list of
            OtherCategoriesSimilarProduct): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "other_categories_similar_product" : "OtherCategoriesSimilarProduct"
    }

    def __init__(self,
                 other_categories_similar_product=None):
        """Constructor for the OtherCategoriesSimilarProducts class"""

        # Initialize members of the class
        self.other_categories_similar_product = other_categories_similar_product


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        other_categories_similar_product = None
        if dictionary.get("OtherCategoriesSimilarProduct") != None:
            other_categories_similar_product = list()
            for structure in dictionary.get("OtherCategoriesSimilarProduct"):
                other_categories_similar_product.append(awsecommerceservice.models.other_categories_similar_product.OtherCategoriesSimilarProduct.from_dictionary(structure))

        # Return an object of this model
        return cls(other_categories_similar_product)


