# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.positive_integer_or_all_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class PositiveIntegerOrAllEnum(object):

    """Implementation of the 'positiveIntegerOrAll' enum.

    TODO: type enum description here.

    Attributes:
        ALL: TODO: type description here.

    """

    ALL = 'All'

