# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.rental_offer

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.merchant
import awsecommerceservice.models.rental_listing

class RentalOffer(object):

    """Implementation of the 'RentalOffer' model.

    TODO: type model description here.

    Attributes:
        merchant (Merchant): TODO: type description here.
        rental_listing (list of RentalListing): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant" : "Merchant",
        "rental_listing" : "RentalListing"
    }

    def __init__(self,
                 merchant=None,
                 rental_listing=None):
        """Constructor for the RentalOffer class"""

        # Initialize members of the class
        self.merchant = merchant
        self.rental_listing = rental_listing


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant = awsecommerceservice.models.merchant.Merchant.from_dictionary(dictionary.get("Merchant")) if dictionary.get("Merchant") else None
        rental_listing = None
        if dictionary.get("RentalListing") != None:
            rental_listing = list()
            for structure in dictionary.get("RentalListing"):
                rental_listing.append(awsecommerceservice.models.rental_listing.RentalListing.from_dictionary(structure))

        # Return an object of this model
        return cls(merchant,
                   rental_listing)


