# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.rental_offers

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.rental_offer

class RentalOffers(object):

    """Implementation of the 'RentalOffers' model.

    TODO: type model description here.

    Attributes:
        rental_offer (list of RentalOffer): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "rental_offer" : "RentalOffer"
    }

    def __init__(self,
                 rental_offer=None):
        """Constructor for the RentalOffers class"""

        # Initialize members of the class
        self.rental_offer = rental_offer


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        rental_offer = None
        if dictionary.get("RentalOffer") != None:
            rental_offer = list()
            for structure in dictionary.get("RentalOffer"):
                rental_offer.append(awsecommerceservice.models.rental_offer.RentalOffer.from_dictionary(structure))

        # Return an object of this model
        return cls(rental_offer)


