# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.similar_viewed_products

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""
import awsecommerceservice.models.similar_viewed_product

class SimilarViewedProducts(object):

    """Implementation of the 'SimilarViewedProducts' model.

    TODO: type model description here.

    Attributes:
        similar_viewed_product (list of SimilarViewedProduct): TODO: type
            description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "similar_viewed_product" : "SimilarViewedProduct"
    }

    def __init__(self,
                 similar_viewed_product=None):
        """Constructor for the SimilarViewedProducts class"""

        # Initialize members of the class
        self.similar_viewed_product = similar_viewed_product


    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        similar_viewed_product = None
        if dictionary.get("SimilarViewedProduct") != None:
            similar_viewed_product = list()
            for structure in dictionary.get("SimilarViewedProduct"):
                similar_viewed_product.append(awsecommerceservice.models.similar_viewed_product.SimilarViewedProduct.from_dictionary(structure))

        # Return an object of this model
        return cls(similar_viewed_product)


