# -*- coding: utf-8 -*-

"""
    awsecommerceservice.models.similarity_type_enum

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
"""

class SimilarityTypeEnum(object):

    """Implementation of the 'SimilarityType' enum.

    TODO: type enum description here.

    Attributes:
        INTERSECTION: TODO: type description here.
        RANDOM: TODO: type description here.

    """

    INTERSECTION = 'Intersection'

    RANDOM = 'Random'

