/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of BrowseNodes243
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('BrowseNodes243', ['BaseModel', BrowseNodes243Model]);

    function BrowseNodes243Model(BaseModel) {
        var BrowseNodes243 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.request = this.getValue(obj.request);
            this.browseNode = this.getValue(obj.browseNode);
        };

        BrowseNodes243.prototype = new BaseModel();
        BrowseNodes243.prototype.constructor = BrowseNodes243;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        BrowseNodes243.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'request', realName: 'Request', type: 'Request162' },
                { name: 'browseNode', realName: 'BrowseNode', array: true, type: 'BrowseNode' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        BrowseNodes243.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Request162|null}
         */
        BrowseNodes243.prototype.getRequest = function () {
            return this.request;
        };
    
        /**
         * Setter for Request
         * 
         * @param {Request162|null} value 
         */
        BrowseNodes243.prototype.setRequest = function (value) {
            this.request = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        BrowseNodes243.prototype.getBrowseNode = function () {
            return this.browseNode;
        };
    
        /**
         * Setter for BrowseNode
         * 
         * @param {array|null} value 
         */
        BrowseNodes243.prototype.setBrowseNode = function (value) {
            this.browseNode = value;
        };
    
        return BrowseNodes243;
    }

}(angular));
