/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of CartCreateRequest55
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('CartCreateRequest55', ['BaseModel', CartCreateRequest55Model]);

    function CartCreateRequest55Model(BaseModel) {
        var CartCreateRequest55 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.mergeCart = this.getValue(obj.mergeCart);
            this.items = this.getValue(obj.items);
            this.responseGroup = this.getValue(obj.responseGroup);
        };

        CartCreateRequest55.prototype = new BaseModel();
        CartCreateRequest55.prototype.constructor = CartCreateRequest55;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        CartCreateRequest55.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'mergeCart', realName: 'MergeCart' },
                { name: 'items', realName: 'Items', type: 'Items' },
                { name: 'responseGroup', realName: 'ResponseGroup', array: true }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        CartCreateRequest55.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        CartCreateRequest55.prototype.getMergeCart = function () {
            return this.mergeCart;
        };
    
        /**
         * Setter for MergeCart
         * 
         * @param {string|null} value 
         */
        CartCreateRequest55.prototype.setMergeCart = function (value) {
            this.mergeCart = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Items|null}
         */
        CartCreateRequest55.prototype.getItems = function () {
            return this.items;
        };
    
        /**
         * Setter for Items
         * 
         * @param {Items|null} value 
         */
        CartCreateRequest55.prototype.setItems = function (value) {
            this.items = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        CartCreateRequest55.prototype.getResponseGroup = function () {
            return this.responseGroup;
        };
    
        /**
         * Setter for ResponseGroup
         * 
         * @param {array|null} value 
         */
        CartCreateRequest55.prototype.setResponseGroup = function (value) {
            this.responseGroup = value;
        };
    
        return CartCreateRequest55;
    }

}(angular));
