/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of MetaData164
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('MetaData164', ['BaseModel', MetaData164Model]);

    function MetaData164Model(BaseModel) {
        var MetaData164 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.keyValuePair = this.getValue(obj.keyValuePair);
        };

        MetaData164.prototype = new BaseModel();
        MetaData164.prototype.constructor = MetaData164;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        MetaData164.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'keyValuePair', realName: 'KeyValuePair', array: true, type: 'KeyValuePair' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        MetaData164.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {array|null}
         */
        MetaData164.prototype.getKeyValuePair = function () {
            return this.keyValuePair;
        };
    
        /**
         * Setter for KeyValuePair
         * 
         * @param {array|null} value 
         */
        MetaData164.prototype.setKeyValuePair = function (value) {
            this.keyValuePair = value;
        };
    
        return MetaData164;
    }

}(angular));
