/**
 * AWSECommerceServiceLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of RelatedItem264
 *
 * @constructor
 */
angular.module('AWSECommerceServiceLib')
    .factory('RelatedItem264', ['BaseModel', RelatedItem264Model]);

    function RelatedItem264Model(BaseModel) {
        var RelatedItem264 = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.item = this.getValue(obj.item);
        };

        RelatedItem264.prototype = new BaseModel();
        RelatedItem264.prototype.constructor = RelatedItem264;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        RelatedItem264.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'item', realName: 'Item', type: 'Item253' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        RelatedItem264.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {Item253|null}
         */
        RelatedItem264.prototype.getItem = function () {
            return this.item;
        };
    
        /**
         * Setter for Item
         * 
         * @param {Item253|null} value 
         */
        RelatedItem264.prototype.setItem = function (value) {
            this.item = value;
        };
    
        return RelatedItem264;
    }

}(angular));
